# Build container based on Debian 10
FROM debian:10

# Install dependencies.
RUN apt-get update \
    && apt-get install -y gcc \
			make \
			vim \
			git \
			gnu-efi \
			libssl-dev \
			libpciaccess-dev \
			uuid-dev \
			libsystemd-dev \
			libevent-dev \
			libxml2-dev \
			libusb-1.0-0-dev \
			python3 \
			python3-pip \
		        libblkid-dev \
			e2fslibs-dev \
			pkg-config \
			zlib1g-dev \
    && apt-get clean

RUN pip3 install kconfiglib

WORKDIR /workspace

CMD ["/bin/bash"]
