# Build container based on Ubuntu 20.04
FROM ubuntu:20.04

# Install dependencies.
RUN apt-get update \
    && DEBIAN_FRONTEND="noninteractive" apt-get install -y gcc make vim git \
                          m4 \
                          libssl-dev \
                          libpciaccess-dev \
                          uuid-dev \
                          libsystemd-dev \
                          libevent-dev \
                          libxml2-dev \
                          libusb-1.0-0-dev \
                          python3 \
                          python3-pip \
                          libblkid-dev \
                          e2fslibs-dev \
                          pkg-config \
                          wget \
                          libnuma-dev \
                          liblz4-tool \
                          flex \
                          bison \
    && apt-get clean

RUN wget https://acpica.org/sites/acpica/files/acpica-unix-20191018.tar.gz && \
   tar zxvf acpica-unix-20191018.tar.gz && \
   cd acpica-unix-20191018 && \
   make clean && \
   make iasl && \
   cp ./generate/unix/bin/iasl /usr/sbin/ && \
   cd ../ && \
   rm -fr acpica-unix-20191018*

RUN pip3 install kconfiglib

WORKDIR /workspace

CMD ["/bin/bash"]
